<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>$(NetCurrent);$(NetFrameworkCurrent)</TargetFrameworks>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <!-- 
      We would need to download 32bit dotnet cli, which would add extra time to PR runs 
      Testing 64bit only on Desktop sufficiently covers our interop code paths.  
    -->
    <TestArchitectures Condition="$([MSBuild]::GetTargetFrameworkIdentifier('$(TargetFramework)')) == '.NETFramework'">x64</TestArchitectures>
    <!-- Copy DSRN to a subdirectory of the output directory, so that we can test alternative load path -->
    <DiaSymReaderNativeLinkDir>DSRN</DiaSymReaderNativeLinkDir>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Microsoft.DiaSymReader\Microsoft.DiaSymReader.csproj" />
    <ProjectReference Include="..\PdbTestResources\PdbTestResources.csproj" />
    <ProjectReference Include="..\TestUtilities\TestUtilities.csproj" />
  </ItemGroup>

  <Import Project="$(RepositoryEngineeringDir)DiaSymReaderNative.targets" />

</Project>
