<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>$(NetCurrent);$(NetFrameworkCurrent)</TargetFrameworks>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Microsoft.DiaSymReader\Microsoft.DiaSymReader.csproj" />
    <ProjectReference Include="..\PdbTestResources\PdbTestResources.csproj" />
    <ProjectReference Include="..\TestUtilities\TestUtilities.csproj" />
  </ItemGroup>

</Project>
